-- MySQL Script generated by MySQL Workbench
-- Fri May 31 20:10:59 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
-- -----------------------------------------------------
-- Schema smartfood
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `smartfood` ;

-- -----------------------------------------------------
-- Schema smartfood
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smartfood` DEFAULT CHARACTER SET utf8 ;
USE `smartfood` ;

create table usuario(
	idUsuario varchar (15) not null primary key,
	nombre varchar (40),
	apellido varchar (40),
	celular varchar (12),
	correo varchar (30),
	contrasena varchar (20)
);

desc usuario;

insert into usuario(idUsuario, nombre, apellido, celular, correo, contrasena) values ("HACHE","MIGUEL","HERNAN","55","l@gmail.com","holamundo");
insert into usuario(idUsuario, nombre, apellido, celular, correo, contrasena) values ("OSCAR","JAIR","LARA","6521736757","lara@gmail.com","crsiete");

select * from usuario;



create table pedido(
	idPedido int not null auto_increment primary key,
	idUsuario varchar(15),
	costo double,
	direccion varchar (40),
	fecha date,
	foreign key (idUsuario) references usuario(idUsuario) on delete cascade on update cascade
);

desc pedido;

insert into pedido(idUsuario, costo, direccion, fecha) 
values ("HACHE",12.5,"Chopin 164, col. P","2019-05-31");
insert into pedido(idUsuario, costo, direccion,fecha) 
values ("OSCAR",18.34,"Norte 48 int 5113, col. L","2019-05-31");

select * from pedido;



create table vegetales(
	idVegetal int not null auto_increment primary key,
	nombre varchar(20),
	costo double
);

desc vegetales;

create table frutas(
	idFruta int not null auto_increment primary key,
	nombre varchar(20),	
	costo double
);

desc frutas;

create table carnes(
	idCarne int not null auto_increment primary key,
	nombre varchar(20),
	costo double
);

desc carnes;

create table aderezos(
	idAderezo int not null auto_increment primary key,
	nombre varchar(20),
	costo double
);

desc aderezos;

insert into vegetales(nombre, costo) values ("Lechuga",5);
insert into vegetales(nombre, costo) values ("Jitomate",5);
insert into vegetales(nombre, costo) values ("Pepino",7);
insert into vegetales(nombre, costo) values ("Aguacate",10);
insert into vegetales(nombre, costo) values ("Cebolla",5);
insert into vegetales(nombre, costo) values ("Zanahorias",10);
insert into vegetales(nombre, costo) values ("Espinacas",7.5);
insert into vegetales(nombre, costo) values ("Papas",9);

select * from vegetales;

insert into frutas(nombre, costo) values ("Mango",10);
insert into frutas(nombre, costo) values ("Kiwi",13.5);
insert into frutas(nombre, costo) values ("Durazno",8.5);
insert into frutas(nombre, costo) values ("Piña",8.5);
insert into frutas(nombre, costo) values ("Naranja",7);
insert into frutas(nombre, costo) values ("Fresa",12.5);
insert into frutas(nombre, costo) values ("Nuez",12.5);
insert into frutas(nombre, costo) values ("Platano",4.5);

select * from frutas;

insert into carnes(nombre, costo) values ("Pollo",20);
insert into carnes(nombre, costo) values ("Atun",22.5);
insert into carnes(nombre, costo) values ("Salmon",27.5);
insert into carnes(nombre, costo) values ("Pastor",15);
insert into carnes(nombre, costo) values ("Bistec",15);
insert into carnes(nombre, costo) values ("Salchicha",9.5);
insert into carnes(nombre, costo) values ("Jamon",10.5);
insert into carnes(nombre, costo) values ("Huevo",14);

select * from carnes;

insert into aderezos(nombre, costo) values ("Ranch",12.5);
insert into aderezos(nombre, costo) values ("Mil islas",12);
insert into aderezos(nombre, costo) values ("Chipotle",10);
insert into aderezos(nombre, costo) values ("Jalapeño",13);
insert into aderezos(nombre, costo) values ("Aceite de oliva",12);
insert into aderezos(nombre, costo) values ("Aceite de coco",22);
insert into aderezos(nombre, costo) values ("Cesar",15);
insert into aderezos(nombre, costo) values ("Wasabi",18.5);

select * from aderezos;

create table pedidov(
	idPedido int not null,
	idVegetal int not null,
	constraint pk_pv primary key(idPedido,idVegetal),
	constraint fk_pvv foreign key(idPedido) references pedido(idPedido),
	constraint fk_v foreign key(idVegetal) references vegetales(idVegetal)
);

desc pedidov;

create table pedidof(
	idPedido int not null,
	idFruta int not null,
	constraint pk_pf primary key(idPedido,idFruta),
	constraint fk_pff foreign key(idPedido) references pedido(idPedido),
	constraint fk_f foreign key(idFruta) references frutas(idFruta)
);

desc pedidof;

create table pedidoc(
	idPedido int not null,
	idCarne int not null,
	constraint pk_pc primary key(idPedido,idCarne),
	constraint fk_pcc foreign key(idPedido) references pedido(idPedido),
	constraint fk_c foreign key(idCarne) references carnes(idCarne)
);

desc pedidoc;

create table pedidoa(
	idPedido int not null,
	idAderezo int not null,
	constraint pk_pa primary key(idPedido,idAderezo),
	constraint fk_paa foreign key(idPedido) references pedido(idPedido),
	constraint fk_a foreign key(idAderezo) references aderezos(idAderezo)
);

desc pedidoa;

insert into pedidov(idPedido,idVegetal) values (1,1);
insert into pedidov(idPedido,idVegetal) values (1,2);
insert into pedidov(idPedido,idVegetal) values (1,4);
insert into pedidov(idPedido,idVegetal) values (1,8);
insert into pedidof(idPedido,idFruta) values (1,2);
insert into pedidof(idPedido,idFruta) values (1,5);
insert into pedidoc(idPedido,idCarne) values (1,2);
insert into pedidoc(idPedido,idCarne) values (1,4);
insert into pedidoa(idPedido,idAderezo) values (1,2);
insert into pedidoa(idPedido,idAderezo) values (1,3);

insert into pedidov(idPedido,idVegetal) values (2,3);
insert into pedidov(idPedido,idVegetal) values (2,5);
insert into pedidov(idPedido,idVegetal) values (2,6);
insert into pedidof(idPedido,idFruta) values (2,1);
insert into pedidof(idPedido,idFruta) values (2,3);
insert into pedidoc(idPedido,idCarne) values (2,1);
insert into pedidoc(idPedido,idCarne) values (2,3);
insert into pedidoa(idPedido,idAderezo) values (2,1);
insert into pedidoa(idPedido,idAderezo) values (2,4);

select * from pedidov;
select * from pedidof;
select * from pedidoc;
select * from pedidoa;

create view vista1 as
select u.nombre, p.idPedido, v.nombre as vegetales 
from usuario u, pedido p, pedidov pv, vegetales v
where u.idUsuario=p.idUsuario
and p.idPedido=pv.idPedido
and pv.idVegetal=v.idVegetal;

create view vista2 as
select u.nombre, p.idPedido, f.nombre as frutas 
from usuario u, pedido p, pedidof pf, frutas f
where u.idUsuario=p.idUsuario
and p.idPedido=pf.idPedido
and pf.idFruta=f.idFruta;

create view vista3 as
select u.nombre, p.idPedido, c.nombre as carnes 
from usuario u, pedido p, pedidoc pc, carnes c
where u.idUsuario=p.idUsuario
and p.idPedido=pc.idPedido
and pc.idCarne=c.idCarne;

create view vista4 as
select u.nombre, p.idPedido, a.nombre as aderezos 
from usuario u, pedido p, pedidoa pa, aderezos a
where u.idUsuario=p.idUsuario
and p.idPedido=pa.idPedido
and pa.idAderezo=a.idAderezo;

select * from vista1;
select * from vista2;
select * from vista3;
select * from vista4;